using TwinCatAutomationKit.TwinCat;

namespace TwinCatAutomationKit.IntegrationTests;

internal sealed record StepCoverageSpec(
    string Kind,
    string Scenario,
    string Dependencies,
    string PassCriteria,
    bool RequiresRuntime = false);

internal static class StepCoverageMatrix
{
    public static IReadOnlyList<StepCoverageSpec> All { get; } =
    [
        Spec("engineering.launch-visual-studio", "ordered-step-surface", "VS DTE registered", "DTE session launches, subsequent XAE template creation succeeds, and later .tsproj evidence proves the session is usable."),
        Spec("engineering.cleanup-dte-host-processes", "unattended cleanup guard", "local process list", "Dry-run lists headless devenv/TcXaeShell candidates without killing windowed IDEs; explicit DryRun=false reports killed/error counts for unattended residue."),
        Spec("engineering.create-xae-solution", "ordered-step-surface", "launch-visual-studio", ".sln and .tsproj are created from the Beckhoff XAE template and later reopened by XAE."),
        Spec("engineering.create-cpp-project", "ordered-step-surface", "create-xae-solution", "Return tree path/display name/file path are deterministic; .vcxproj ProjectGuid and .tmc exist."),
        Spec("engineering.create-vs-cpp-project", "ordered-step-surface", "create-xae-solution", "A regular VS C++ console project is created or template fallback is explicitly requested; .sln/.vcxproj/DTE model all expose it."),
        Spec("engineering.create-scope-project", "ordered-step-surface and OptCNC parity", "open solution", "A new .tcmproj and optional empty .tcscopex are generated by the step, the .sln contains the Scope project GUID/path, and no sample Scope metadata is copied."),
        Spec("scope.ensure-configuration", "ordered-step-surface and OptCNC parity", "generated Scope .tcscopex path", "A typed Scope configuration request creates ADS acquisitions and YT chart channels with exact symbols, ports, offsets, and acquisition links without copying sample Scope XML."),
        Spec("scope.assert-configuration-shape", "ordered-step-surface and OptCNC guard", "generated or reopened Scope .tcscopex", "The Scope guard parses .tcscopex and proves the expected Scope name, chart name, ADS channel count, chart channel count, symbol names, and channel acquisition links."),
        Spec("engineering.ensure-solution-project-dependency", "ordered-step-surface", "create-vs-cpp-project and create-xae-solution", ".sln artifact contains ProjectSection(ProjectDependencies) with exact AdsClient and ItProject GUIDs from the VS C++ project to the TwinCAT project."),
        Spec("engineering.create-io-device", "ordered-step-surface and OptCNC IO parity", "open XAE solution", "XAE ITcSmTreeItem.CreateChild creates or finds an IO Device under TIID, using subtype/vInfo rather than copied Project/Io XML; export/describe evidence proves it persisted."),
        Spec("engineering.create-ethercat-box", "ordered-step-surface and OptCNC IO parity", "open XAE solution with EtherCAT parent", "XAE ITcSmTreeItem.CreateChild creates or finds an EtherCAT box/terminal with subtype 9099 and ProductRevision/vInfo so XAE/ESI generates PDO and process-image metadata."),
        Spec("engineering.generate-io-mappings", "ordered-step-surface and OptCNC IO parity", "open XAE solution with IO topology", "ITcSmCommands.GenerateMappings or an explicitly enabled DTE fallback runs under timeout, then IO/root Mappings guards prove the generated mappings were retained."),
        Spec("engineering.search-io-devices", "ordered-step-surface and OptCNC IO parity", "open XAE solution on a machine with IO driver state", "ITcSmCommands.SearchDevices runs under timeout without menu fallback, then TIID export or topology guards prove the resulting IO tree."),
        Spec("engineering.reload-io-devices", "ordered-step-surface and OptCNC IO parity", "open XAE solution with IO devices", "ITcSmCommands.ReloadDevices runs under timeout without menu fallback, then TIID export or topology guards prove regenerated device metadata."),
        Spec("engineering.apply-io-tree-plan", "ordered-step-surface and OptCNC IO parity", "open XAE solution", "Batch wrapper applies device/box CreateChild requests in order and returns XAE tree paths; topology guards prove generated IO metadata."),
        Spec("ethercat.assert-product-revisions", "ordered-step-surface and OptCNC IO parity", "installed Beckhoff EtherCAT ESI XML files", "File-only guard scans installed ESI XML and proves productRevision/vInfo strings used by CreateChild are present before XAE IO tree creation."),
        Spec("engineering.create-plc-project", "ordered-step-surface", "create-xae-solution", "PLC project/instance names are readable, MAIN.TcPOU is replaced, and build/ADS later prove the PLC payload loaded."),
        Spec("engineering.create-module", "ordered-step-surface", "create-cpp-project", "Aux module returns the requested name, writes header/source/TMC metadata, and full-project reopen/export accepts it; fallback is allowed but not counted as strict wizard evidence."),
        Spec("engineering.start-tmc-code-generator", "ordered-step-surface", "create-cpp-project/create-module", "StartTmcCodeGenerator is invoked on the C++ project; .tmc remains readable and exact module/source-derived metadata is available for later instance creation."),
        Spec("engineering.publish-modules", "ordered-step-surface", "create-cpp-project/create-module", "PublishModules is invoked; .tmc artifact remains readable and contains exact AuxModule TMC metadata, with updated output recording timestamp/hash changes when present."),
        Spec("engineering.verify-tmc-data-areas", "ordered-step-surface", "generated C++ project .tmc", "The .tmc is parsed directly and expected module DataAreas/symbols are verified before instance creation."),
        Spec("engineering.apply-tmc-module-model", "ordered-step-surface", "generated C++ project .tmc and Services.h", "Structured JSON module metadata is applied to the .tmc, custom type GUIDs are resolved from Services.h, and verify-tmc-data-areas confirms the resulting module shape."),
        Spec("engineering.add-module-instance", "ordered-step-surface", "create-cpp-project/create-module", "Primary and auxiliary instances return parseable ObjectIds, expected display names, exact .tsproj identities, and reopen/export acceptance even if fallback was used."),
        Spec("engineering.ensure-task", "ordered-step-surface", "create-xae-solution", "Two tasks return parseable ObjectIds and reopen with exact priority/cycle/AMS port/affinity/layout."),
        Spec("engineering.export-tree-item-xml", "ordered-step-surface", "created C++ project/tasks", "TIXC and TIRT ProduceXml snapshots must not be fallback, and XML is parsed for TreeItem root, ItemName, PathName, subtype, and non-empty content."),
        Spec("engineering.save-all", "ordered-step-surface", "open solution", "Saved .tsproj survives close/reopen and later build."),
        Spec("engineering.close-visual-studio", "ordered-step-surface", "open solution", "Session closes before .tsproj file mutation; cleanup also closes the final session."),
        Spec("engineering.open-xae-solution", "ordered-step-surface", "closed solution after file mutation", "Mutated .tsproj reopens and tree export works."),
        Spec("engineering.build-solution", "ordered-step-surface", "PLC-only runtime clone", "BuildCurrentSolution returns Succeeded=true and LastBuildInfo=0, then non-empty PLC .tmc/.compileinfo output files must exist and at least one is updated in this run."),
        Spec("engineering.activate-configuration", "activation-ads-runtime", "built scenario, EnableActivation=true", "ActivateConfiguration succeeds, records the activation command, restarts TwinCAT, and writes a non-empty archive with solution/config evidence.", RequiresRuntime: true),

        Spec("cpp.create-project-item", "ordered-step-surface", "created C++ project", "A .cpp/.h/.rc/None item is created inside the project directory, registered in .vcxproj, mapped to .filters when requested, and survives reopen."),
        Spec("cpp.write-project-item-content", "ordered-step-surface", "created C++ project item", "Payload content is written through the public step, output SHA256 matches file bytes, and the item remains registered."),
        Spec("cpp.remove-project-item", "ordered-step-surface", "created C++ project with template/default or synthetic item", ".vcxproj and .filters artifacts no longer contain the exact Generated/StepProbe.license item, and the physical file path is deleted when requested."),
        Spec("cpp.set-project-property", "ordered-step-surface", "created C++ project", ".vcxproj XML artifact contains the exact CharacterSet value under the requested PropertyGroup, and later build proves the project remains valid."),
        Spec("cpp.set-item-definition-property", "ordered-step-surface", "created C++ project", ".vcxproj XML artifact contains exact ClCompile LanguageStandard/include path or Link metadata values under ItemDefinitionGroup with requested condition."),
        Spec("cpp.set-project-item-metadata", "ordered-step-surface", "registered C++ project item", ".vcxproj XML artifact contains exact ExcludedFromBuild or PrecompiledHeader metadata under the requested item, and atomic output records the metadata step."),

        Spec("signing.set-license", "signing-metadata", "built C++ project with stale signing metadata", "A single TcSign PropertyGroup is written with EnableSigning=false, exact license name, no password, and no duplicate or stale signing nodes."),
        Spec("signing.grant-certificate", "excluded-signing-certificate", "local TwinCAT OEM signing certificate/private key", "Excluded from default real-machine verification; exclusion is explicit evidence in matrix/README and no fake certificate output is accepted."),
        Spec("signing.sign-twincat-binary", "excluded-signing-certificate", "local TwinCAT OEM signing certificate/private key and built .tmx", "Excluded from default real-machine verification because a real OEM signing credential is machine/vendor state."),
        Spec("signing.verify-twincat-binary", "excluded-signing-certificate", "signed built .tmx", "Excluded from default real-machine verification because sign is excluded without a real OEM signing credential or signed binary evidence."),

        Spec("tsproj.ensure-task", "ordered-step-surface", "created .tsproj", "RuntimeTask and AuxTask .tsproj attributes are exact after duplicate ensure and XAE reopen."),
        Spec("tsproj.clear-task-layout", "ordered-step-surface", "AuxTask with deliberately stale Vars/Image", "Stale AuxTask Vars/Image are inserted first, removed by clear, and absent after deterministic layout rebuild."),
        Spec("tsproj.ensure-task-vars-group", "ordered-step-surface", "AuxTask", "Input and output Vars groups are rebuilt with exact VarGrpType/InsertType/count/type/offset/external address."),
        Spec("tsproj.ensure-task-image", "ordered-step-surface", "AuxTask", "Task Image Id/address type/image type/size/name attributes are exact and later reopen succeeds."),
        Spec("tsproj.ensure-cpp-instance", "ordered-step-surface", "C++ project", "FileMutationCpp01 instance skeleton is inserted with exact ObjectId, context priority/cycle, and TmcDesc containers."),
        Spec("tsproj.ensure-plc-instance", "ordered-step-surface", "PLC project", "PLC instance node exists before PLC metadata and vars mutations."),
        Spec("tsproj.bind-instance-context", "ordered-step-surface", "aux instance, aux task ObjectId", "Aux instance context ManualConfig/CyclicCaller XML points at exact AuxTask ObjectId after reopen."),
        Spec("tsproj.bind-instance-task", "ordered-step-surface", "primary instance, runtime task ObjectId", "Primary instance context ManualConfig/CyclicCaller XML points at exact RuntimeTask ObjectId after reopen."),
        Spec("tsproj.bind-plc-instance-task", "ordered-step-surface", "PLC instance, runtime task ObjectId", "PLC context ManualConfig XML points at exact RuntimeTask ObjectId and runtime ADS runtime-only InitSymbol proof uses it."),
        Spec("tsproj.set-task-affinity", "ordered-step-surface", "RuntimeTask/AuxTask", "Affinity and AdtTasks .tsproj attributes are written for both tasks and survive XAE reopen."),
        Spec("tsproj.set-plc-project-properties", "ordered-step-surface", "PLC project", "PLC project AmsPort, ReloadTmc, path, and archive attributes are normalized."),
        Spec("tsproj.set-plc-instance-metadata", "ordered-step-surface", "PLC instance", "PLC instance metadata attributes and exact CLSID/ClassFactory XML are written without replacing vars."),
        Spec("tsproj.clear-plc-instance-vars", "ordered-step-surface", "PLC instance with deliberately stale Vars", "Stale PLC Vars are inserted first, removed by clear, and absent after deterministic inputs/outputs are rebuilt."),
        Spec("tsproj.ensure-plc-instance-vars-group", "ordered-step-surface", "PLC instance", "PLC input/output Vars groups are present with exact VarGrpType/InsertType/AreaNo/type/offset/external address."),
        Spec("tsproj.set-cpp-instance-metadata", "ordered-step-surface and atomic-wrapper", "primary/aux C++ instances", "C++ instance metadata attributes such as Disabled are set without replacing TmcDesc or value sections."),
        Spec("tsproj.clear-plc-init-symbols", "ordered-step-surface", "PLC instance with a stale InitSymbol", "A stale InitSymbol is inserted first, removed by clear, and absent after ObjectId-derived InitSymbols are recreated."),
        Spec("tsproj.clear-plc-task-pou-oids", "ordered-step-surface", "PLC instance with a stale priority-99 TaskPouOid", "A stale TaskPouOid is inserted first, removed by clear, and absent after the runtime TaskPouOid is recreated."),
        Spec("tsproj.ensure-task-pou-oid", "ordered-step-surface", "PLC instance, runtime task ObjectId", "TaskPouOid stores the runtime task ObjectId and priority."),
        Spec("tsproj.ensure-init-symbol", "ordered-step-surface", "PLC instance, runtime/aux task ObjectIds", "InitSymbol Type/GUID/AreaNo/Data contain ObjectId-derived bytes, and a runtime-only ADS symbol proves InitSymbols, not PLC defaults, set the value."),
        Spec("tsproj.replace-data-types-section", "ordered-step-surface", "created .tsproj with a stale DataType section", "A stale DataType section is written first, then replaced; only deterministic test types and merge audit type remain."),
        Spec("tsproj.replace-system-settings-section", "ordered-step-surface", "created .tsproj with stale Settings marker", "A stale Settings marker is written first, then replaced; the marker is absent while Tasks remain available."),
        Spec("tsproj.ensure-system-settings", "ordered-step-surface", "created .tsproj with System/Tasks", "Typed System/Settings Cpu and IoIdleTask attributes are upserted without replacing Tasks or using a raw Settings fragment."),
        Spec("tsproj.replace-project-io-section", "ordered-step-surface", "created .tsproj with stale Io section", "A stale Io section is written first, then replaced by the JSON-owned non-runtime-critical section."),
        Spec("tsproj.ensure-io-section", "ordered-step-surface", "created .tsproj", "Project/Io is created through the dedicated primitive and survives XAE reopen alongside other Project children."),
        Spec("tsproj.ensure-io-device", "ordered-step-surface", "Project/Io", "A structured IO Device is created with exact Id/Name/DevType/AMS/AddressInfo XML fields and no whole-section replacement."),
        Spec("tsproj.ensure-ethercat-box", "ordered-step-surface", "structured IO Device", "Nested EtherCAT Box XML is created under the requested Device/parent Box with exact Id/Name/ImageId/EtherCAT attributes."),
        Spec("tsproj.ensure-io-box-image", "ordered-step-surface", "structured IO Box", "Box ImageId and metadata child XML are updated without replacing the Box or losing nested topology."),
        Spec("tsproj.ensure-io-pdo", "ordered-step-surface", "structured EtherCAT Box", "Box/EtherCAT/Pdo XML contains exact Name/Index/Flags/SyncMan and Entry Type fields after reopen."),
        Spec("tsproj.ensure-mapping-info", "ordered-step-surface", "root Mappings", "Root Mappings/MappingInfo XML contains the exact Identifier and ObjectId pair exactly once."),
        Spec("tsproj.ensure-io-mapping-link", "ordered-step-surface", "structured IO topology and root Mappings", "IO-to-TcCOM mapping Link XML contains exact OwnerA/OwnerB/Var paths plus optional mapping attributes."),
        Spec("tsproj.apply-io-topology-plan", "ordered-step-surface", "dedicated IO topology primitives", "Batch IO topology JSON creates Device, Box, Pdo, MappingInfo, and Link XML through dedicated primitives and returns exact counts."),
        Spec("tsproj.ensure-io-task-image", "ordered-step-surface", "RuntimeTask, primary instance", "RuntimeTask Image id/size/name and primary instance IoTaskImage pointer are created together with exact ObjectId."),
        Spec("tsproj.clear-instance-parameter-values", "ordered-step-surface", "primary/aux instances with stale parameters", "Stale parameter values are inserted first, removed by clear, and absent after plan application."),
        Spec("tsproj.apply-instance-parameter-plan", "ordered-step-surface", "primary/aux instances", "Batch parameter plan writes exact primary and aux Parameter.data1 values, which survive XAE reopen."),
        Spec("tsproj.ensure-parameter", "ordered-step-surface and atomic-wrapper", "primary instance", "Single parameter upsert is idempotent after batch plan and wrapper path writes its own exact probe value."),
        Spec("tsproj.apply-instance-interface-pointer-plan", "ordered-step-surface", "primary/aux instances, task ObjectIds", "Batch interface pointer plan writes exact CyclicCaller ObjectId XML values for both instances."),
        Spec("tsproj.ensure-interface-pointer", "ordered-step-surface", "aux instance, task ObjectId", "Single interface pointer upsert is idempotent after batch plan and exact ObjectId XML remains unchanged."),
        Spec("tsproj.clear-instance-data-pointer-values", "ordered-step-surface and atomic-wrapper", "primary/aux instances with stale data pointers", "Stale DataPointerValues are inserted first, removed by clear, and absent after deterministic data pointer plan restore."),
        Spec("tsproj.apply-instance-data-pointer-plan", "ordered-step-surface and atomic-wrapper", "primary/aux instances", "Batch data pointer plan writes exact OTCID/AreaNo/ByteOffs/ByteSize values for DataIn/DataOut."),
        Spec("tsproj.refresh-cpp-instance-tmc-desc", "ordered-step-surface", "C++ instances and project .tmc", "Existing C++ instance TmcDesc sections are refreshed from the project .tmc while context and value sections remain intact."),
        Spec("tsproj.ensure-data-pointer", "ordered-step-surface", "primary instance", "Single data pointer upsert is idempotent after batch plan and exact values survive XAE reopen."),
        Spec("tsproj.assert-data-pointer-shape", "ordered-step-surface and OptCNC guard", "instances with DataPointerValues and root Mappings", "The observed DataPointerValues record count, expected pointer entries, and required root mapping links match the requested JSON guard."),
        Spec("tsproj.assert-io-topology-shape", "ordered-step-surface and OptCNC guard", "Project/Io and root Mappings", "The observed Device, Box, PDO, MappingInfo, OwnerA, and Link counts plus requested IO owners/links match the JSON guard without mutating IO metadata."),
        Spec("tsproj.assert-io-image-references", "ordered-step-surface and OptCNC guard", "Project/Io process-image references", "The observed root ImageData, direct Device/Image, Device InfoImageId, and ImageId reference shape is internally consistent without mutating IO metadata."),
        Spec("tsproj.describe-io-topology", "ordered-step-surface and OptCNC guard", "Project/Io and root Mappings", "The normalized read-only IO topology JSON exposes device, box, PDO, mapping, and optional attribute summaries without copying raw metadata XML."),
        Spec("tsproj.compare-io-topology", "ordered-step-surface and OptCNC guard", "two .tsproj files", "The normalized read-only comparison reports count, missing Device/Box/PDO, and mapping-link differences without importing reference metadata XML."),
        Spec("tsproj.clear-mappings", "ordered-step-surface", "created .tsproj with stale mapping link", "Stale mapping links are inserted first, removed by clear, and absent after deterministic links are rebuilt."),
        Spec("tsproj.replace-mappings-section", "ordered-step-surface", "created .tsproj with stale Mappings section", "Root Mappings is replaced with a stale known-good section and then an empty section before deterministic links are rebuilt."),
        Spec("tsproj.clear-unrestored-var-links", "ordered-step-surface and atomic-wrapper", "created .tsproj with stale UnrestoredVarLinks", "Stale UnrestoredVarLinks blocks are inserted first and absent after clear before reopen/build or wrapper verification."),
        Spec("tsproj.ensure-mapping-link", "ordered-step-surface", "PLC vars and C++ process image names", "Four PLC/C++ mapping links are present and full-project reopen/export succeeds."),
        Spec("tsproj.upsert-element", "ordered-step-surface", "Project/System path", "Generic element upsert writes exact attributes and child values under the intended parent."),
        Spec("tsproj.upsert-fragment", "ordered-step-surface", "Project/System path", "Generic fragment upsert writes a matched named fragment with exact child values."),
        Spec("tsproj.apply-mutation-plan", "ordered-step-surface", "Project/System path", "Batch generic mutation plan writes exact element and fragment child values, and valid+invalid failure leaves .tsproj byte-for-byte unchanged."),
        Spec("tsproj.merge-fragment", "ordered-step-surface", "unique DataTypes parent and required evidence fields", "Documented named fragment merge succeeds, leaves exactly the expected DataTypes set, and reopen/build accepts the file."),

        Spec("validation.ads-scan", "activation-ads-runtime", "EnableAdsRead=true, running ADS router/runtime", "The configured runtime ADS port must report a readable state, not merely any scanned port.", RequiresRuntime: true),
        Spec("validation.assert-ads-state", "activation-ads-runtime", "EnableAdsRead=true, running ADS router/runtime", "Configured ADS ports must match their expected ADS state so activation false positives fail deterministically.", RequiresRuntime: true),
        Spec("validation.mark-event-log-window", "activation-ads-runtime and unattended guard", "Windows Application event log", "The current TcSysSrv event-log position is recorded without launching VS so activation can be bounded to a marker.", RequiresRuntime: true),
        Spec("validation.assert-event-log-window", "activation-ads-runtime and unattended guard", "Windows Application event log marker", "The activation window fails if TcSysSrv writes Error/Critical events or AdsState >15< Config messages.", RequiresRuntime: true),
        Spec("validation.assert-process-crash-window", "activation-ads-runtime and unattended guard", "Windows Application event log marker", "The activation or XAE-open window fails if devenv/TcXaeShell or TwinCAT System Manager crash events appear, so RPC disconnects are diagnosed as host crashes.", RequiresRuntime: true),
        Spec("validation.ads-read-symbols", "activation-ads-runtime", "EnableAdsRead=true, valid symbol list", "Batch ADS read must return the configured parameter, deterministic conversion result, task ObjectId probes, runtime-only InitSymbol probe, checksum, transform-ok flag, and mismatch count with exact expected values.", RequiresRuntime: true),
        Spec("validation.ads-read", "activation-ads-runtime", "EnableAdsRead=true, deterministic runtime symbol", "Single-symbol ADS read of MAIN.nConfiguredParameter must return the exact configured value used by the strict batch runtime proof.", RequiresRuntime: true),
    ];

    public static IReadOnlyList<string> MissingCatalogKinds()
    {
        HashSet<string> documented = All.Select(item => item.Kind).ToHashSet(StringComparer.OrdinalIgnoreCase);
        return TwinCatStepCatalog.All
            .Select(item => item.Kind)
            .Where(kind => !documented.Contains(kind))
            .OrderBy(kind => kind, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    public static IReadOnlyList<string> UnknownMatrixKinds()
    {
        HashSet<string> catalog = TwinCatStepCatalog.All.Select(item => item.Kind).ToHashSet(StringComparer.OrdinalIgnoreCase);
        return All
            .Select(item => item.Kind)
            .Where(kind => !catalog.Contains(kind))
            .OrderBy(kind => kind, StringComparer.OrdinalIgnoreCase)
            .ToList();
    }

    private static StepCoverageSpec Spec(
        string kind,
        string scenario,
        string dependencies,
        string passCriteria,
        bool RequiresRuntime = false) =>
        new(kind, scenario, dependencies, passCriteria, RequiresRuntime);
}
